using Memori.Models;

namespace Memori.Abstractions;

/// <summary>
/// Represents a stored conversation for a session.
/// </summary>
public sealed record Conversation
{
    static string requireNonEmpty(string value, string paramName)
    {
        if (string.IsNullOrWhiteSpace(value))
            throw new ArgumentException("Value cannot be empty.", paramName);

        return value;
    }

    /// <summary>
    /// Creates a conversation model.
    /// </summary>
    public Conversation(string id, string sessionId, DateTimeOffset createdAt, DateTimeOffset updatedAt,
        string? summary = null)
    {
        Id = requireNonEmpty(id, nameof(id));
        SessionId = requireNonEmpty(sessionId, nameof(sessionId));
        CreatedAt = createdAt;
        UpdatedAt = updatedAt;
        Summary = summary;
    }

    /// <summary>
    /// Public storage identifier for the conversation.
    /// </summary>
    public string Id { get; }

    /// <summary>
    /// Public storage identifier for the session this conversation belongs to.
    /// </summary>
    public string SessionId { get; }

    /// <summary>
    /// Optional rolling summary generated by augmentation.
    /// </summary>
    public string? Summary { get; init; }

    /// <summary>
    /// Time the conversation was created.
    /// </summary>
    public DateTimeOffset CreatedAt { get; }

    /// <summary>
    /// Time the conversation was last updated.
    /// </summary>
    public DateTimeOffset UpdatedAt { get; init; }
}

/// <summary>
/// Stores and retrieves Memori's conversation and session data.
/// </summary>
/// <remarks>
/// <para>
/// This interface covers the relational/ordered operations that do not benefit from
/// vector search: entities, processes, sessions, conversations, and messages.
/// </para>
/// <para>
/// Implementations are expected to be safe for concurrent use by multiple
/// requests. All get-or-create methods must be idempotent for the same logical
/// external identifier.
/// </para>
/// </remarks>
public interface IConversationStorage
{
    /// <summary>
    /// Gets or creates an entity and returns its public storage identifier.
    /// </summary>
    /// <param name="externalId">External entity identifier, usually a user id.</param>
    /// <param name="scope">Optional workspace/scope identifier for multi-tenant isolation.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The public storage identifier for the entity.</returns>
    ValueTask<string> GetOrCreateEntityAsync(
        string externalId,
        string? scope = null,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets or creates a process and returns its public storage identifier.
    /// </summary>
    /// <param name="externalId">External process or workflow identifier.</param>
    /// <param name="scope">Optional workspace/scope identifier for multi-tenant isolation.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The public storage identifier for the process.</returns>
    ValueTask<string> GetOrCreateProcessAsync(
        string externalId,
        string? scope = null,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets or creates a session and returns its public storage identifier.
    /// </summary>
    /// <param name="sessionId">External session identifier.</param>
    /// <param name="entityId">Public storage identifier for the entity, if available.</param>
    /// <param name="processId">Public storage identifier for the process, if available.</param>
    /// <param name="scope">Optional workspace/scope identifier for multi-tenant isolation.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The public storage identifier for the session.</returns>
    ValueTask<string> GetOrCreateSessionAsync(
        string sessionId,
        string? entityId,
        string? processId,
        string? scope = null,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets the active conversation for a session or creates a new one when the
    /// last conversation is older than <paramref name="timeout"/>.
    /// </summary>
    /// <param name="sessionId">Public storage identifier for the session.</param>
    /// <param name="timeout">Maximum inactivity before a new conversation is created.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The active conversation.</returns>
    ValueTask<Conversation> GetOrCreateConversationAsync(
        string sessionId,
        TimeSpan timeout,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Appends messages to a conversation in the order provided.
    /// </summary>
    /// <param name="conversationId">Public storage identifier for the conversation.</param>
    /// <param name="messages">Messages to append.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    ValueTask AppendMessagesAsync(
        string conversationId,
        IReadOnlyList<ConversationMessage> messages,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Reads all messages for a conversation in insertion order.
    /// </summary>
    /// <param name="conversationId">Public storage identifier for the conversation.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Conversation messages in insertion order.</returns>
    ValueTask<IReadOnlyList<ConversationMessage>> GetConversationMessagesAsync(
        string conversationId,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Updates a conversation summary.
    /// </summary>
    /// <param name="conversationId">Public storage identifier for the conversation.</param>
    /// <param name="summary">Summary text.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    ValueTask UpdateConversationSummaryAsync(
        string conversationId,
        string summary,
        CancellationToken cancellationToken = default);
}
