namespace Memori.Models;

/// <summary>
/// Represents a stored conversation for a session.
/// </summary>
public sealed record Conversation
{
    static string requireNonEmpty(string value, string paramName)
    {
        if (string.IsNullOrWhiteSpace(value))
            throw new ArgumentException("Value cannot be empty.", paramName);

        return value;
    }

    /// <summary>
    /// Creates a conversation model.
    /// </summary>
    public Conversation(string id, string sessionId, DateTimeOffset createdAt, DateTimeOffset updatedAt,
        string? summary = null)
    {
        Id = requireNonEmpty(id, nameof(id));
        SessionId = requireNonEmpty(sessionId, nameof(sessionId));
        CreatedAt = createdAt;
        UpdatedAt = updatedAt;
        Summary = summary;
    }

    /// <summary>
    /// Public storage identifier for the conversation.
    /// </summary>
    public string Id { get; }

    /// <summary>
    /// Public storage identifier for the session this conversation belongs to.
    /// </summary>
    public string SessionId { get; }

    /// <summary>
    /// Optional rolling summary generated by augmentation.
    /// </summary>
    public string? Summary { get; init; }

    /// <summary>
    /// Time the conversation was created.
    /// </summary>
    public DateTimeOffset CreatedAt { get; }

    /// <summary>
    /// Time the conversation was last updated.
    /// </summary>
    public DateTimeOffset UpdatedAt { get; init; }
}
